sudo: required

language: node_js

services:
  - docker

before_install:
  - docker build -t siomiz/node-opencv .

install: true

script:
  - docker run siomiz/node-opencv bash -c "npm install opencv && node -p \"require('opencv')\""
